<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net9.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
    <UseWindowsForms>true</UseWindowsForms>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <ApplicationIcon>fan.ico</ApplicationIcon>
    <AssemblyName>FanWidget</AssemblyName>
    <RootNamespace>FanWidget</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <None Update="fan.ico">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="LibreHardwareMonitorLib" Version="0.9.7-pre726" />
    <PackageReference Include="System.Management" Version="10.0.11" />
  </ItemGroup>

</Project>
